url: "https://loicknuchel.fr"
title: "Loïc Knuchel"
logo: "/assets/img/avatar.jpg"
hireme: true
permalink: /blog/:year/:month/:day/:title

collections:
  work_experiences:
    date: true
    slug: true
    name: true
    duration: true
    website: true
    logo: true
    twitter: true
    tags: true

plugins:
  - jemoji
  - jekyll-sitemap

defaults:
  - # jekyll-sitemap config
    scope:
      path: "v1"
    values:
      sitemap: false

exclude: ['.idea']
