exclude: ['.idea']

permalink: /blog/:categories/:year/:month/:day/:title

hireme: true

collections:
  work_experiences:
    date: true
    slug: true
    name: true
    duration: true
    website: true
    logo: true
    twitter: true
    tags: true
